package config

internal object EnvKeys {
    const val IBLOG_BUILD_NUMBER = "IBLOG_BUILD_NUMBER"
    const val IBLOG_ANDROID_KEYSTORE_ALIAS = "IBLOG_ANDROID_KEYSTORE_ALIAS"
    const val IBLOG_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD = "BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD"
    const val IBLOG_ANDROID_KEYSTORE_PASSWORD = "BITRISEIO_ANDROID_KEYSTORE_PASSWORD"
}