ktor {
  deployment {
    port = 8080
    watch = [ server ]
  }
  security {
      jwt {
        issuer = "ktor-user-api"
        audience = "ktor-user-api-client"
        realm = "poyopoyo"
        secret = ${?JWT_SECRET} # Injection using environment variables
        expiresInMs = 3600000   # 1h
        }
  }
   application {
    modules = [ com.poyopoyo.userapi.ApplicationKt.module ]
   }
  database {
      # SQLDelight + SQLite
      jdbcUrl = "jdbc:sqlite:./build/devdb.sqlite"
    }
}
